#!/usr/bin/env perl
use strict;
use warnings;
use eleMentalClinic;

=head1 NAME

elementalclinic_fixture_import

=head1 SYNOPSIS

Import the contents of a specified fixture dataset into the eMC database.

=cut

$|++;

use Getopt::Long;

use lib 'lib';
use eleMentalClinic::Fixtures;

my @paths;
my $dups = 1;
GetOptions(
    "help"            => \&help,
    "fixtures=s{,}"   => \@paths,
    "dups!"           => \$dups,
);

die( "$0: No directories specified for loading.\nTry `$0 --help` for more information.\n" ) unless @paths;

print "Importing fixture data...";
my $test = eleMentalClinic::Fixtures->new;
for my $path ( @paths ) {
    $test->insert_fixture_data( $path, $dups );
}
print "done.\n";

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sub help {
    print STDERR <<"EOF";
Usage: $0 [options]

    This program is used to load fixture datasets from specified
directories. By specifying any number of directories after the -f
or --fixtures option, all fixture datafiles in those directories
will be compiled and imported into the database.

Options:
   -h   --help      Display this help message.
   -f   --fixtures  Supply a list of fixture directories to load
        --nodups    Skip inserting rows which already exist
EOF
    exit( 0 );
}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



__END__

=head1 AUTHORS

=over 4

=item Ryan Whitehurst L<ryan@opensourcery.com>

=back

=head1 BUGS

We strive for perfection but are, in fact, mortal.  Please see
L<https://prefect.opensourcery.com:444/projects/elementalclinic/report/1> for
known bugs.

=head1 SEE ALSO

=over 4

=item Project web site at: L<http://elementalclinic.org>

=item Code management site at: L<https://prefect.opensourcery.com:444/projects/elementalclinic/>

=back

=head1 COPYRIGHT

Copyright (C) 2008 OpenSourcery, LLC

This file is part of eleMental Clinic.

eleMental Clinic is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option) any
later version.

eleMental Clinic is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
Street, Fifth Floor, Boston, MA 02110-1301 USA.

eleMental Clinic is packaged with a copy of the GNU General Public License.
Please see docs/COPYING in this distribution.
